{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"bank_loan_data\",\"Measure Table\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.963.0 (23.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "81b6a678-0684-479e-a576-56eb272f3b0b",
        "fromColumn": "last_credit_pull_date",
        "fromTable": "bank_loan_data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bdf92a54-0739-4c67-a409-8552c7335a38"
      },
      {
        "name": "c6272c04-7a23-4621-823b-7335763b9874",
        "fromColumn": "last_payment_date",
        "fromTable": "bank_loan_data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_033af34f-042b-4a59-bf00-41fcdd4dcb2c"
      },
      {
        "name": "058f45b9-508a-42ac-b657-36e62a56b228",
        "fromColumn": "next_payment_date",
        "fromTable": "bank_loan_data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_220cfcc5-154b-4c02-8ad9-2ee746822d10"
      },
      {
        "name": "e0f4b63b-5c3e-47fd-8f70-11b1d6b3fd30",
        "fromColumn": "Date",
        "fromTable": "Date Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_79349e33-b262-492f-9698-c2166afbb9ba"
      },
      {
        "name": "79e08988-08e3-4ea8-acb5-001664ea86d8",
        "fromColumn": "issue_date",
        "fromTable": "bank_loan_data",
        "toColumn": "Date",
        "toTable": "Date Table"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "bank_loan_data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "58f58b2f-b39a-43d9-a71b-a13b039a0937",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "address_state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "428c44cb-24f4-4aa1-9690-40a0cdbdaafe",
            "sourceColumn": "address_state",
            "summarizeBy": "none"
          },
          {
            "name": "application_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b605b8a3-e669-46cb-b384-169c4956cac4",
            "sourceColumn": "application_type",
            "summarizeBy": "none"
          },
          {
            "name": "emp_length",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed6f5bd8-79e5-42ae-83be-fe2d619d854a",
            "sourceColumn": "emp_length",
            "summarizeBy": "none"
          },
          {
            "name": "emp_title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d61db637-35a6-412b-8808-01160db22811",
            "sourceColumn": "emp_title",
            "summarizeBy": "none"
          },
          {
            "name": "grade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b00b4353-abb6-4773-825c-d9d699d7475c",
            "sourceColumn": "grade",
            "summarizeBy": "none"
          },
          {
            "name": "home_ownership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7689d7e9-ac40-4407-88b3-8cd43c49bc87",
            "sourceColumn": "home_ownership",
            "summarizeBy": "none"
          },
          {
            "name": "issue_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a734103d-6e68-4058-9acc-3d4ffad83d16",
            "sourceColumn": "issue_date",
            "summarizeBy": "none"
          },
          {
            "name": "last_credit_pull_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "90f58789-7901-4844-826d-d79695696ce8",
            "sourceColumn": "last_credit_pull_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bdf92a54-0739-4c67-a409-8552c7335a38"
                },
                "isDefault": true,
                "relationship": "81b6a678-0684-479e-a576-56eb272f3b0b"
              }
            ]
          },
          {
            "name": "last_payment_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "baeb6d6c-eb91-4629-8035-47913d668782",
            "sourceColumn": "last_payment_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_033af34f-042b-4a59-bf00-41fcdd4dcb2c"
                },
                "isDefault": true,
                "relationship": "c6272c04-7a23-4621-823b-7335763b9874"
              }
            ]
          },
          {
            "name": "loan_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"bank_loan_data\",\"TableItemName\":\"Good v Bad Loan\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5039218-0c31-4319-8f70-e4ebb2caec4e",
            "sourceColumn": "loan_status",
            "summarizeBy": "none"
          },
          {
            "name": "next_payment_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5f8d7114-09da-4cf0-b81d-ee134b7f1aef",
            "sourceColumn": "next_payment_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_220cfcc5-154b-4c02-8ad9-2ee746822d10"
                },
                "isDefault": true,
                "relationship": "058f45b9-508a-42ac-b657-36e62a56b228"
              }
            ]
          },
          {
            "name": "member_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "61f6eb27-9af1-4319-8ee8-1bd8dab0e24f",
            "sourceColumn": "member_id",
            "summarizeBy": "sum"
          },
          {
            "name": "purpose",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7b8cb9e-9fe6-47be-b55f-18a466bc1c85",
            "sourceColumn": "purpose",
            "summarizeBy": "none"
          },
          {
            "name": "sub_grade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "169ffdf7-12bb-40a4-8bda-246afe142ee2",
            "sourceColumn": "sub_grade",
            "summarizeBy": "none"
          },
          {
            "name": "term",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "092e2364-32b2-4258-aaac-90f741d0fe5e",
            "sourceColumn": "term",
            "summarizeBy": "none"
          },
          {
            "name": "verification_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7251e4ac-9b40-40a2-bed6-63d3349a8cd0",
            "sourceColumn": "verification_status",
            "summarizeBy": "none"
          },
          {
            "name": "annual_income",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "95b368db-fc14-4b4a-b315-4ea88e59212b",
            "sourceColumn": "annual_income",
            "summarizeBy": "sum"
          },
          {
            "name": "dti",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4d46d9b3-2cad-47f5-a548-d2463ad6c113",
            "sourceColumn": "dti",
            "summarizeBy": "sum"
          },
          {
            "name": "installment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "71863713-2078-493f-85cb-22126e3476f6",
            "sourceColumn": "installment",
            "summarizeBy": "sum"
          },
          {
            "name": "int_rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7d400f16-e605-47e0-bacb-14b9f6ff8b96",
            "sourceColumn": "int_rate",
            "summarizeBy": "sum"
          },
          {
            "name": "loan_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68ccd993-6ce8-48c8-802d-b4ccf73b562e",
            "sourceColumn": "loan_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "total_acc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "585043ea-5c5d-4023-919d-429722c6f98a",
            "sourceColumn": "total_acc",
            "summarizeBy": "sum"
          },
          {
            "name": "total_payment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6441ccaa-b45a-4b7b-8416-549cef078c08",
            "sourceColumn": "total_payment",
            "summarizeBy": "sum"
          },
          {
            "name": "Good v Bad Loan",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"b\",\"Entity\":\"bank_loan_data\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"b\"}},\"Property\":\"loan_status\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Bad Loan\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"b\"}},\"Property\":\"loan_status\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Charged Off'\"}}]]}}},{\"DisplayName\":\"Good Loan\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"b\"}},\"Property\":\"loan_status\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Current'\"}}],[{\"Literal\":{\"Value\":\"'Fully Paid'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('bank_loan_data'[loan_status]),",
              "\t\"(Blank)\",",
              "\t'bank_loan_data'[loan_status] IN {\"Charged Off\"},",
              "\t\"Bad Loan\",",
              "\t'bank_loan_data'[loan_status] IN {\"Current\",",
              "\t\t\"Fully Paid\"},",
              "\t\"Good Loan\",",
              "\t'bank_loan_data'[loan_status]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "bank_loan_data"
                          }
                        },
                        "Property": "loan_status"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "dd562560-0ed2-4b6d-858d-97fd1fa20a27",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "bd5abb98-d360-4de0-a096-5c793d2ec430",
        "partitions": [
          {
            "name": "bank_loan_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"Sneha\\SQLEXPRESS02\", \"bi_project_files\"),",
                "    dbo_bank_loan_data = Source{[Schema=\"dbo\",Item=\"bank_loan_data\"]}[Data]",
                "in",
                "    dbo_bank_loan_data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_e91a9427-c050-4a6d-96aa-d18f2e3c7fb6",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f454cc8e-f058-4e1d-819c-643461ea501f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba48b80d-0770-4870-99ec-01c10c4af9bc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "10772bf1-7965-4c39-848e-a40b266931f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "22da185c-1c89-422e-b81c-d26048a3fa53",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7e225262-bc3a-4609-a6cd-e58963d4f859",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "128e8473-8420-407b-9b36-30cc2b6ef182",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0a9d9394-6ed9-4da1-b8a2-d9c1175cac74",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "202cebe1-bcd7-44c8-8c24-1c3efdc1857f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fddd24d6-1438-49e5-b603-3daf87372b50",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8173bafc-d5c8-4b6e-ad2c-993cc1566fd7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4c00b5d2-9a85-4724-b4cc-2660dd3fd81a",
                "ordinal": 3
              }
            ],
            "lineageTag": "5883d55b-91f3-4ee4-941d-56b1f5f5646a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "2d18a3f9-c2c4-4afb-b9d4-7e6bb4491156",
        "partitions": [
          {
            "name": "DateTableTemplate_e91a9427-c050-4a6d-96aa-d18f2e3c7fb6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bdf92a54-0739-4c67-a409-8552c7335a38",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d0b13bc6-81cb-43f0-bf03-017d71bcdf47",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "af306ec0-32e0-4eaa-919a-b339d8851221",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d643756c-dd08-4f2f-a257-d914b8547eaa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9898e459-4fed-4a03-b16c-911760e0b0e9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7b6ff6c4-71c7-4595-b160-e2390a5e2148",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e3524cc3-1cfe-4d37-bc4f-79b785ea4d49",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7c96866b-2b8b-4f27-b7ce-265d6956579e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2451d23a-3f80-40bb-915f-3a539996ce7e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1e745dd9-a5cd-40c1-b382-b47d2705edc8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8dee26dd-2b3f-49b3-8de0-d4d5685f1ab2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "663613e8-4e19-44da-b356-fa06a4c7509c",
                "ordinal": 3
              }
            ],
            "lineageTag": "01526efd-6efd-4b1b-83fd-63ba976bf308"
          }
        ],
        "isHidden": true,
        "lineageTag": "e224e177-66d4-480f-b7c2-e97b1b099c10",
        "partitions": [
          {
            "name": "LocalDateTable_bdf92a54-0739-4c67-a409-8552c7335a38",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('bank_loan_data'[last_credit_pull_date])), 1, 1), Date(Year(MAX('bank_loan_data'[last_credit_pull_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_033af34f-042b-4a59-bf00-41fcdd4dcb2c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5c39b0f1-c59c-47dc-ac27-e8235eeffb78",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a6fc067c-eb60-4285-b3de-9d16e605eb17",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "da1e52c9-53df-4d5a-89f9-b52588ab55e1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fa6655c3-3ddd-41f5-9d5f-0307aa44d813",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f6ce61d8-3596-4df1-8404-66cfe973b9e0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cb555fd1-0fa0-4c21-9bd6-612e452f4f35",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d2cac838-1c59-4187-9520-1c2f62318c19",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "57e652c8-2ef7-4721-a321-72120371a73f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "62c0d799-5509-4eb5-bc52-73046d96960a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "749fa89a-fe13-47e6-a62a-2c18500dcc13",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "50067594-69aa-4889-88ab-defad223bb3a",
                "ordinal": 3
              }
            ],
            "lineageTag": "fdd6c345-ff05-45c8-b3b5-c68b89c29296"
          }
        ],
        "isHidden": true,
        "lineageTag": "4136a569-851d-4082-b67f-b97b2c6f61c6",
        "partitions": [
          {
            "name": "LocalDateTable_033af34f-042b-4a59-bf00-41fcdd4dcb2c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('bank_loan_data'[last_payment_date])), 1, 1), Date(Year(MAX('bank_loan_data'[last_payment_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_220cfcc5-154b-4c02-8ad9-2ee746822d10",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "70976bba-c4cc-4267-84c1-64354d6862be",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c9218e9b-c152-454a-8d71-c37a74ea6c11",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f72c84ea-8f61-48b2-be82-ba5be8fbcbaa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3a4a435e-9c79-4c2c-a43c-d76bf462d72e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "41bfb647-477a-4dd1-8669-869b08d64401",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8acb205c-5786-4491-a8c8-bb7ab385ea27",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9b163826-fd9a-484f-b93d-e1d6c15d81b5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "60f6ace7-dcfa-423a-bde1-4d4fd17685a8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "84bcbe22-881a-4e32-93dc-bf898199adad",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "099dbcf1-1913-4b1f-8010-7604e5a02469",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d03a3587-c1dd-4582-8551-eb3476075bb1",
                "ordinal": 3
              }
            ],
            "lineageTag": "d7b20cef-b46c-4b88-88d1-c3b316d1f588"
          }
        ],
        "isHidden": true,
        "lineageTag": "17edbc4d-ac00-431c-8870-a3580a70059e",
        "partitions": [
          {
            "name": "LocalDateTable_220cfcc5-154b-4c02-8ad9-2ee746822d10",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('bank_loan_data'[next_payment_date])), 1, 1), Date(Year(MAX('bank_loan_data'[next_payment_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Date Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "60a132c997834b06be5f3e0fb9101524"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dcbce7ea-76e6-4106-8505-5b586374c57e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_79349e33-b262-492f-9698-c2166afbb9ba"
                },
                "isDefault": true,
                "relationship": "e0f4b63b-5c3e-47fd-8f70-11b1d6b3fd30"
              }
            ]
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT('Date Table'[Date], \"mmm\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "736d69a8-f79c-4154-aaef-493abb36dac6",
            "sortByColumn": "Month Number",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT('Date Table'[Date], \"dd\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "50fad872-f85f-4b2a-8a60-534c47e2f942",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT('Date Table'[Date], \"dddd\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "5bc06a3e-a540-4475-be75-677bb4107db9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "WEEKNUM('Date Table'[Date].[MonthNo])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1c182ab0-e755-4ccd-8296-3465208658be",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "    MONTH('Date Table'[Date])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a027fbdb-aa4b-418e-b614-801b490acd11",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "234c0602-6fd3-4e03-a291-dce8843eb73f",
        "partitions": [
          {
            "name": "Date Table",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "CALENDAR(MIN(bank_loan_data[issue_date]), MAX(bank_loan_data[issue_date]))"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_79349e33-b262-492f-9698-c2166afbb9ba",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "356392fa-6c47-4b4d-9e9a-896216007de4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "17a74ebd-7a45-4bc5-ba79-b438d4b17abc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ccbd703e-97b1-4dad-99c1-bcdb54ebcf44",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bbaeb1ee-5b4c-4e28-9944-a734064fcdd7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "60d7461e-fa24-4c7d-b5d3-a756d113bf95",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2c3896b2-c5e4-44e5-b944-82ae1341d31d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1e24bbf9-ccd9-47ff-8064-bece19154048",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0e0ddeba-1437-4877-aac3-aa44a2350ec7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f929a681-f6f4-4970-8311-226b69e2e08b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ac7454ad-ad7c-4191-8625-67fba86a72e0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "dd9aeef3-623b-4dd6-9f22-d0d949905532",
                "ordinal": 3
              }
            ],
            "lineageTag": "45211966-2c1b-4ffd-ad67-b0ea04b455dc"
          }
        ],
        "isHidden": true,
        "lineageTag": "8fecd143-f47a-4ef7-8290-e63db2269cfc",
        "partitions": [
          {
            "name": "LocalDateTable_79349e33-b262-492f-9698-c2166afbb9ba",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date Table'[Date])), 1, 1), Date(Year(MAX('Date Table'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Measure Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "41b5a2b0-9939-4246-a23e-5351bdecbb5f",
        "measures": [
          {
            "name": "Total Loan Application",
            "expression": [
              "",
              "    COUNT(bank_loan_data[id])"
            ],
            "formatString": "0",
            "lineageTag": "6fd3f03e-1de3-4a84-a61b-24cf3d76ead4"
          },
          {
            "name": "MTD Loan Application",
            "expression": [
              "",
              "CALCULATE(",
              "    TOTALMTD(",
              "        [Total Loan Application],",
              "        'Date Table'[Date]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "319873e0-7996-4da7-8d0e-cbe0bc8dbd78"
          },
          {
            "name": "PMTD Loan Application",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Loan Application],",
              "        DATESMTD(DATEADD('Date Table'[Date], -1, MONTH))",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "a8b20f89-6742-4795-b3be-7c054eff60d3"
          },
          {
            "name": "MOM Loan Application",
            "expression": [
              "",
              "    DIVIDE(",
              "        [MTD Loan Application] - [PMTD Loan Application],",
              "        [PMTD Loan Application],",
              "        0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "57045e57-34b5-4f3c-820e-ff7742220e58"
          },
          {
            "name": "Total Funded Amount",
            "expression": [
              "",
              "    SUM(bank_loan_data[loan_amount])"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7b7e1bc7-4920-4644-a43d-9403dbad5eea"
          },
          {
            "name": "MTD Funded Amount",
            "expression": [
              "",
              "CALCULATE(",
              "    TOTALMTD(",
              "        [Total Funded Amount],",
              "        'Date Table'[Date]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a71614a2-a778-4862-b85d-a95d03cad2b4"
          },
          {
            "name": "PMTD Funded Amount",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Funded Amount],",
              "        DATESMTD(DATEADD('Date Table'[Date], -1, MONTH))",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "6fc3adf5-c6fb-4b31-8604-e534a185b292"
          },
          {
            "name": "MOM Funded Amount",
            "expression": [
              "",
              "    DIVIDE(",
              "        [MTD Funded Amount] - [PMTD Funded Amount],",
              "        [PMTD Funded Amount],",
              "        0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "79dd4dc1-8a70-4ade-b0ce-ef8d74315fa2"
          },
          {
            "name": "Total Amount Received",
            "expression": [
              "",
              "    SUM(bank_loan_data[total_payment])"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e4022f2d-2ebd-464b-bb94-9fa57f3530ff"
          },
          {
            "name": "MTD Received Amount",
            "expression": [
              "",
              "    CALCULATE(",
              "        TOTALMTD(",
              "            [Total Amount Received],",
              "            'Date Table'[Date]",
              "        ))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "698a967a-10d7-4d87-af89-59d4d871f8f4"
          },
          {
            "name": "PMTD Received Amount",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Amount Received],",
              "        DATESMTD(",
              "            DATEADD('Date Table'[Date], -1, MONTH)",
              "        )",
              "    )   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "135bff00-234c-4951-9c25-74300012dba9"
          },
          {
            "name": "MOM Received Amount",
            "expression": [
              "",
              "    DIVIDE(",
              "        [MTD Received Amount] - [PMTD Received Amount],",
              "        [PMTD Received Amount],",
              "        0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6366e36d-d307-476e-961a-3e51695dda84"
          },
          {
            "name": "AVG Interest Rate",
            "expression": [
              "",
              "    AVERAGE(bank_loan_data[int_rate])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a5a3753c-caa4-48ef-a08a-e07a6f181a4a"
          },
          {
            "name": "MTD Interest Rate",
            "expression": [
              "",
              "    CALCULATE(",
              "        TOTALMTD(",
              "            [AVG Interest Rate],",
              "            'Date Table'[Date]",
              "        )",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5b2755c2-ea56-4254-9285-d1c48fb4f44b"
          },
          {
            "name": "PMTD Interest Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [AVG Interest Rate],",
              "        DATESMTD(",
              "            DATEADD('Date Table'[Date], -1, MONTH)",
              "        )",
              "    )"
            ],
            "lineageTag": "c43a3614-a73f-4216-a811-39260b045cf2"
          },
          {
            "name": "MOM Interest Rate",
            "expression": [
              "",
              "    DIVIDE(",
              "        [MTD Interest Rate] - [PMTD Interest Rate],",
              "        [PMTD Interest Rate],",
              "        0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f1b90f85-5b45-40e7-9d46-02686aef251a"
          },
          {
            "name": "AVG DTI",
            "expression": [
              "",
              "    AVERAGE(bank_loan_data[dti])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3a271e48-58d8-4b91-a1f0-1f87df38b69c"
          },
          {
            "name": "MTD DTI",
            "expression": [
              "",
              "CALCULATE(",
              "    TOTALMTD(",
              "        [AVG DTI],",
              "        'Date Table'[Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "308e7811-160a-4001-a071-437fe2d527e1"
          },
          {
            "name": "PMTD DTI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [AVG DTI],",
              "        DATESMTD(",
              "            DATEADD('Date Table'[Date], -1, MONTH)",
              "        )",
              "    )"
            ],
            "lineageTag": "a9eecbaa-9f8d-4d3a-85c8-6a3179492289"
          },
          {
            "name": "MOM DTI",
            "expression": [
              "",
              "    DIVIDE(",
              "        [MTD DTI] - [PMTD DTI],",
              "        [PMTD DTI],",
              "        0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7a3515c6-ffd8-4a5f-9911-da8f0b030a17"
          },
          {
            "name": "Good Loan %",
            "expression": [
              "",
              "    DIVIDE(",
              "        CALCULATE(",
              "            [Total Loan Application],",
              "            bank_loan_data[Good v Bad Loan] = \"Good Loan\"",
              "        ),",
              "        [Total Loan Application],",
              "        0",
              "    )",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b17a1f4b-4498-4fa3-95f0-e79e2ad1e41b"
          },
          {
            "name": "Good Loan Application",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Loan Application],",
              "        bank_loan_data[Good v Bad Loan] = \"Good Loan\"",
              "    )"
            ],
            "formatString": "0.00",
            "lineageTag": "3967b263-5be4-4fb6-87e2-55190e5bc5ea"
          },
          {
            "name": "Good Loan Funde Amount",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Funded Amount],",
              "        bank_loan_data[Good v Bad Loan] = \"Good Loan\"",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "4478a9bb-ba7c-44b2-9fdc-abb6afa42a6c"
          },
          {
            "name": "Good Loan Amount Received",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Amount Received],",
              "        bank_loan_data[Good v Bad Loan] = \"Good Loan\"",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "4c176570-539f-4824-8398-8f133cefd073"
          },
          {
            "name": "Bad Loan %",
            "expression": [
              "",
              "    DIVIDE(",
              "        CALCULATE(",
              "            [Total Loan Application],",
              "            bank_loan_data[Good v Bad Loan] = \"Bad Loan\"",
              "        ),",
              "        [Total Loan Application],",
              "        0",
              "    )",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "eab2f0f8-fd8e-4726-9806-56afc3331af2"
          },
          {
            "name": "Bad Loan Application",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Loan Application],",
              "        bank_loan_data[Good v Bad Loan] = \"Bad Loan\"",
              "    )"
            ],
            "formatString": "0.00",
            "lineageTag": "a6362fbb-7fc1-4b4d-a584-f41bd08dc7ec"
          },
          {
            "name": "Bad Loan Funde Amount",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Funded Amount],",
              "        bank_loan_data[Good v Bad Loan] = \"Bad Loan\"",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "6b1f1176-5547-4428-ba9c-f76c22262d25"
          },
          {
            "name": "Bad Loan Amount Received",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Amount Received],",
              "        bank_loan_data[Good v Bad Loan] = \"Bad Loan\"",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "066619d8-c104-4f11-bd0d-ca1aae49df7c"
          }
        ],
        "partitions": [
          {
            "name": "Measure Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Select Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "764b3cd0e20545b2b4dd6903393e258d"
          }
        ],
        "columns": [
          {
            "name": "Select Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "dd99e667-e145-4cbb-8c10-98a0f3ed7a69",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Select Measure Fields"
                }
              ]
            },
            "sortByColumn": "Select Measure Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Select Measure Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "db953cdb-29bc-49b4-a83f-afe390bd6c09",
            "sortByColumn": "Select Measure Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Select Measure Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "52342b58-73ba-481d-acbe-0723fd816051",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "06c0d79e-bb0b-46d6-b121-80bbad407737",
        "partitions": [
          {
            "name": "Select Measure",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Amount Received\", NAMEOF('Measure Table'[Total Amount Received]), 0),",
                "    (\"Total Funded Amount\", NAMEOF('Measure Table'[Total Funded Amount]), 1),",
                "    (\"Total Loan Application\", NAMEOF('Measure Table'[Total Loan Application]), 2)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}